input:
  generate:
    count: 1
    mapping: root = {"id":"1"}

pipeline:
  processors:
    - log:
        message: "input"
        fields_mapping: |
          json = content().string()
          traceID = tracing_id()
    - grpc:
        address: "app2:50052"
tracer:
  open_telemetry_collector:
    grpc:
      - address: "jaeger:4317"
    sampling:
      enabled: false
      ratio: 0.85 # No default (optional)
    tags:
      service.name: app1